apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: incident
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-db
  namespace: incident
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incident-db
  template:
    metadata:
      labels:
        app: incident-db
    spec:
      serviceAccountName: incident-manager-sa
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      containers:
      - name: postgres
        image: bitnami/postgresql:16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: chimchim95
        - name: POSTGRES_DB
          value: incidentDB
        volumeMounts:
        - mountPath: /bitnami/postgresql
          name: postgres-storage
        securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
            runAsNonRoot: true
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: incident-db
  namespace: incident
spec:
  selector:
    app: incident-db
  ports:
    - port: 5432
      targetPort: 5432
