
services:
  jenkins:
    build:     
      context: ./jenkins
      dockerfile: Dockerfile
    image: custom-jenkins:dev
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
      - JAVA_OPTS=-Xmx512m -Xms512m
    networks:
      - devsecops-net
    mem_limit: 2g          
    cpus: 2.0 
  k3s:
    image: rancher/k3s:latest
    container_name: k3s
    privileged: true
    ports:
      - "32458:32458"
      - "32459:32459"
      - "6443:6443"
      - "30008:30009"
      - "30006:30006"
      - "30007:30007"
      - "31241:31241"
      - "31237:31237"
      - "31238:31238"
      - "80:80"
      - "30010:30010"
      - "30011:30011"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - k3s_data:/var/lib/rancher/k3s
    environment:
      - K3S_KUBEVIRT_CONTAINER=1
    command: server --disable traefik --disable servicelb
    

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_WEB_JAVA_OPTS=-Xmx512m -Xms512m
    depends_on:
      - postgres
    networks:
      - devsecops-net
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g  

  postgres:
    image: postgres:latest
    container_name: sonarqube_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - devsecops-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512m  

  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      
    ports:
      - 9200:9200
    networks:
      - devsecops-net
    deploy:
      resources:
        limits:
          cpus: '1.0'      
          memory: 1g   

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200  
      NODE_OPTIONS: --max-old-space-size=1024
      xpack.encryptedSavedObjects.encryptionKey: UneChaineTresLongueEtSecrete1234567890
      xpack.reporting.encryptionKey: UneAutreChaineTresLongueEtSecrete9876543210
      xpack.security.enabled: false
    ports:
      - 5601:5601
    networks:
      - devsecops-net
    deploy:
      resources:
        limits:
          cpus: '1.0'      
          memory: 512m    
  

networks:
  devsecops-net:
    driver: bridge

volumes:
  jenkins_home:
  k3s_data:
  postgres_data:
  
  
  
