apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-secure-app-binding-incident
  namespace: incident
subjects:
- kind: ServiceAccount
  name: my-secure-app-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: my-secure-app-role
  apiGroup: rbac.authorization.k8s.io
