apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc 
  namespace: incident
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-db 
  namespace: incident
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incident-db
  template:
    metadata:
      labels:
        app: incident-db
    spec:
      serviceAccountName: my-secure-app-sa 
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: chimchim95
        - name: POSTGRES_DB
          value: incidentDB
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
        securityContext:         # <--- ADD THIS
          allowPrivilegeEscalation: false
          
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: incident-db
  namespace: incident
spec:
  selector:
    app: incident-db
  ports:
    - port: 5432
      targetPort: 5432
