apiVersion: v1
kind: Pod
metadata:
  name: test-secure-pod
  namespace: incident
spec:
  serviceAccountName: my-secure-app-sa
  containers:
  - name: test-container
    image: nginx:latest
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
